CREATE TABLE IF NOT EXISTS user_profiles (
  user_id BIGINT NOT NULL PRIMARY KEY,
  nickname VARCHAR(64) NOT NULL,
  avatar VARCHAR(255) NOT NULL DEFAULT '',
  activation_code VARCHAR(64) NOT NULL DEFAULT '',
  is_admin BOOLEAN NOT NULL DEFAULT FALSE,
  balance BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_user_profiles_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS legacy_post_states (
  post_id BIGINT NOT NULL PRIMARY KEY,
  attachment_price BIGINT NOT NULL DEFAULT 0,
  visibility INT NOT NULL DEFAULT 0,
  is_lock BOOLEAN NOT NULL DEFAULT FALSE,
  is_top BOOLEAN NOT NULL DEFAULT FALSE,
  is_essence BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_legacy_post_states_post_id FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS legacy_comment_states (
  comment_id BIGINT NOT NULL PRIMARY KEY,
  is_essence BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_legacy_comment_states_comment_id FOREIGN KEY (comment_id) REFERENCES comments(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comment_replies (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  comment_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  at_user_id BIGINT NOT NULL DEFAULT 0,
  content TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_comment_replies_comment_id FOREIGN KEY (comment_id) REFERENCES comments(id) ON DELETE CASCADE,
  CONSTRAINT fk_comment_replies_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX idx_comment_replies_comment_id (comment_id),
  INDEX idx_comment_replies_user_id (user_id)
);

CREATE TABLE IF NOT EXISTS comment_reactions (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  post_id BIGINT NOT NULL,
  comment_id BIGINT NOT NULL,
  reply_id BIGINT NOT NULL DEFAULT 0,
  target_type TINYINT NOT NULL,
  is_thumbs_up BOOLEAN NOT NULL DEFAULT FALSE,
  is_thumbs_down BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_comment_reactions_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT uq_comment_reactions_target UNIQUE KEY (user_id, comment_id, reply_id, target_type),
  INDEX idx_comment_reactions_comment_id (comment_id),
  INDEX idx_comment_reactions_reply_id (reply_id)
);

CREATE TABLE IF NOT EXISTS friendships (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  friend_id BIGINT NOT NULL,
  status TINYINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_friendships_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_friendships_friend_id FOREIGN KEY (friend_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT uq_friendships_pair UNIQUE KEY (user_id, friend_id),
  INDEX idx_friendships_friend_id (friend_id)
);

ALTER TABLE messages
  ADD COLUMN type TINYINT NOT NULL DEFAULT 4 AFTER receiver_user_id,
  ADD COLUMN brief VARCHAR(255) NOT NULL DEFAULT '' AFTER type,
  ADD COLUMN post_id BIGINT NOT NULL DEFAULT 0 AFTER content,
  ADD COLUMN comment_id BIGINT NOT NULL DEFAULT 0 AFTER post_id,
  ADD COLUMN reply_id BIGINT NOT NULL DEFAULT 0 AFTER comment_id;

CREATE TABLE IF NOT EXISTS wallet_recharges (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  amount BIGINT NOT NULL,
  trade_no VARCHAR(128) NOT NULL DEFAULT '',
  trade_status VARCHAR(64) NOT NULL DEFAULT 'PENDING',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_wallet_recharges_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX idx_wallet_recharges_user_id (user_id)
);

CREATE TABLE IF NOT EXISTS wallet_statements (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  change_amount BIGINT NOT NULL,
  balance_snapshot BIGINT NOT NULL,
  reason VARCHAR(255) NOT NULL,
  post_id BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_wallet_statements_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX idx_wallet_statements_user_id (user_id)
);

CREATE TABLE IF NOT EXISTS phone_captchas (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  phone VARCHAR(32) NOT NULL,
  captcha VARCHAR(16) NOT NULL,
  use_times INT NOT NULL DEFAULT 0,
  expired_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_phone_captchas_phone_created_at (phone, created_at)
);
