[package]
name = "evt-app"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "evt"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
axum.workspace = true
evt-config = { path = "../config" }
evt-grpc-api = { path = "../grpc-api" }
evt-http-api = { path = "../http-api" }
evt-infra = { path = "../infra" }
tokio.workspace = true
tonic.workspace = true
opentelemetry.workspace = true
opentelemetry-otlp.workspace = true
opentelemetry_sdk.workspace = true
tracing.workspace = true
tracing-opentelemetry.workspace = true
tracing-subscriber.workspace = true
