[package]
name = "paopao-app"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "paopao-ce"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
axum.workspace = true
paopao-config = { path = "../config" }
paopao-grpc-api = { path = "../grpc-api" }
paopao-http-api = { path = "../http-api" }
paopao-infra = { path = "../infra" }
tokio.workspace = true
tonic.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
